services:

  traefik:
    image: traefik:v3.3.6
    container_name: synapse_traefik
    command:
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:81
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letls.acme.email=serebryansky@keeneye.pro
      - --certificatesresolvers.letls.acme.storage=/certs/acme.json
      - --certificatesresolvers.letls.acme.httpchallenge=true
      - --certificatesresolvers.letls.acme.httpchallenge.entrypoint=web
    ports:
      - "443:443"
      - "81:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/certs

  nginx:
    image: nginx:1.27.5
    container_name: synapse_nginx
    volumes:
      - nginx_conf:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`iskra.ru`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=letls

  synapse_db:
    image: docker.io/postgres:17
    container_name: synapse_db
    environment:
      - POSTGRES_USER=sadmin
      - POSTGRES_PASSWORD=sadmin
      - POSTGRES_DB=synapse_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse_db_data:/var/lib/postgresql/data

  synapse:
    image: docker.io/matrixdotorg/synapse:v1.128.0
    container_name: synapse
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - synapse_data:/data
    depends_on:
      - synapse_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.synapse.entrypoints=websecure
      - traefik.http.routers.synapse.rule=Host(`matrix.iskra.ru`)
      - traefik.http.routers.synapse.tls=true
      - traefik.http.routers.synapse.tls.certresolver=letls

volumes:
  traefik_certs:
  nginx_conf:
  synapse_data:
  synapse_db_data:
