version: '3.9'
services:
  postgresdb:
    image: 'postgres:15'
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=database_name
      - POSTGRES_PASSWORD=pass