version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
      - db_config_data:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sadmin
      - MONGO_INITDB_ROOT_PASSWORD=sadmin
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "7080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=sadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=sadmin
      - ME_CONFIG_MONGODB_URL=mongodb://sadmin:sadmin@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo
    driver: bridge

volumes:
  db_data:
  db_config_data:
